#ifndef __IEditorBrowseFrame__
#define __IEditorBrowseFrame__

/**
@file
Subclass of BrowseFrame, which is generated by wxFormBuilder.
*/

#include "IEditor.h"

//// end generated include

/** Implementing BrowseFrame */
class IEditorBrowseFrame : public BrowseFrame
{
	public:
		/** Constructor */
		IEditorBrowseFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __IEditorBrowseFrame__
